### PR TITLE
update inspec.yml

### PR DESCRIPTION
**Pull request by MoisesTapia**
the value default is deprecated and in the new versions of inspec we need change the value default for value

### CODE REVIEW

**Comment by MoisesTapia** [comment]
the value default is deprecated and in the new versions of inspec we need change the value default for value

**Comment by chris-rock** [comment]
@MoisesTapia Great improvement. Can you sign off the commits please?

**Comment by MoisesTapia** [comment]
I try to sing off but git return me a error:
remote: Permission to dev-sec/cis-docker-benchmark.git denied to MoisesTapia.
fatal: unable to access 'https://github.com/dev-sec/cis-docker-benchmark/': The requested URL returned error: 403

**Comment by micheelengronne** [comment]
Sign on your own repository. On `https://github.com/MoisesTapia/cis-docker-benchmark`

**Comment by MoisesTapia** [comment]
I am trying to sign it from my repository but I cannot what are the command to sign it?

**Comment by micheelengronne** [comment]
Click on `Details` on the DCO line in the `Some checks were not successful`.

**Comment by MoisesTapia** [comment]
Done

**Comment by micheelengronne** [comment]
It is still not green. Is your local git email the same as the one you set on Github ? It should be ?

**Comment by MoisesTapia** [comment]
yes it's the same ...

This commit was signed with a verified signature. 

commit

**Comment by micheelengronne** [comment]
Yes, I saw it. It is your previous commits you must also sign.

**Comment by MoisesTapia** [comment]
sorry but, how can I do it

**Comment by micheelengronne** [comment]
I think you should squash your commits into one and sign off this resulting commit.

Here is a tutorial on how to accomplish that https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by micheelengronne** [comment]
I you are unsure of what you do, do a backup of your git repo as incorrectly rewriting a git history can lead to commit loss (data loss).

**Pull request closed without merging**
