### PR TITLE
Update Inspec.yml

### PR DESCRIPTION
**Pull request by MoisesTapia**
some values of Inspec.yml for new versions of Inspec

### CODE REVIEW

**Comment by MoisesTapia** [comment]
Done ....

**Comment by MoisesTapia** [comment]
@chris-rock  all checks passed

**Comment by MoisesTapia** [comment]
@micheelengronne all checks passed

**Comment by micheelengronne** [comment]
Is it the same as https://github.com/dev-sec/cis-docker-benchmark/pull/64 ?

**Pull request merged**
