### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by netflash**
Fix renamed repo

### CODE REVIEW

**Comment by atomic111** [comment]
@netflash thanks for your PR, but at first i have to fix the testing issue or maybe you will do it

**Comment by netflash** [comment]
I'll have a look, thanks.
BTW you sure you still want to test over EOL versions of ruby ?

**Comment by atomic111** [comment]
oh, you are right. you can remove the old ruby version. thanks for the hint

**Comment by atomic111** [comment]
great, thank you @netflash

**Pull request merged**
