### PR TITLE
Edit control "cis-docker-benchmark-1.11"

### PR DESCRIPTION
**Pull request by emilyh315**
Edited the control so that it referred to the docker.socket file, not the docker.service file. Edited the description and test.

### CODE REVIEW

**Comment by atomic111** [comment]
@emilyh315 thank you for the fix. befor i can merge your PR. i have to figure out and correct the travis error.

**Comment by atomic111** [comment]
@emilyh315 can you please rebase your PR. we updated the repo and now the tests are working

**Comment by chris-rock** [comment]
@emilyh315 can you please sign off your commit as well?

**Comment by atomic111** [comment]
@emilyh315 great, thank you

**Pull request merged**
